basePath: /api/v1
definitions:
  main.customer:
    properties:
      country:
        type: string
      countrycode:
        type: integer
      customertype:
        type: string
      id:
        type: string
      name:
        type: string
      phonenumber:
        type: integer
      verified:
        type: string
    type: object
info:
  contact: {}
paths:
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /registration/customers:
    get:
      description: Responds with the list of all customers as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.customer'
            type: array
      summary: Get customers array
      tags:
      - customers
    post:
      consumes:
      - application/json
      description: Takes a customer JSON and store in DB. Return saved JSON.
      parameters:
      - description: customer Data
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/main.customer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.customer'
      summary: Store a new customer
      tags:
      - newcustomer
swagger: "2.0"
